/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author JuanJ
 */
public class Plano extends javax.swing.JPanel {

    /**
     * Creates new form Plano
     */
    private int[] aux = new int[8];

    public Plano(int[] aux) {
        this.aux = aux;
        initComponents();
    }

    public void paint(Graphics g) {
        Graphics2D figura = (Graphics2D) g;
        figura.setStroke(new BasicStroke(8.f));
        figura.setColor(Color.red);
        /*
        figura.drawLine(10, 50, 100, 50);
        figura.drawLine(100, 50, 100, 200);
        figura.drawLine(100, 200, 10, 200);
        figura.drawLine(10, 200, 10, 50);
        */
        figura.drawLine(aux[0],aux[1],aux[2],aux[3]);
        figura.drawLine(aux[2],aux[3],aux[4],aux[5]);
        figura.drawLine(aux[4],aux[5],aux[6],aux[7]);
        figura.drawLine(aux[6],aux[7],aux[0],aux[1]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
