/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi;

import javax.swing.JOptionPane;

/**
 *
 * @author JuanJ
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    public void dibujar(int[] aux) {
        Plano plano = new Plano(aux);
        plano.setBounds(200, 10, 250, 250);
        panelPlano.removeAll();
        panelPlano.add(plano);
        panelPlano.revalidate();
        panelPlano.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuadrado = new javax.swing.JLabel();
        lblX1 = new javax.swing.JLabel();
        lblX2 = new javax.swing.JLabel();
        lblX3 = new javax.swing.JLabel();
        lblX4 = new javax.swing.JLabel();
        campX1 = new javax.swing.JTextField();
        campX2 = new javax.swing.JTextField();
        campX3 = new javax.swing.JTextField();
        campX4 = new javax.swing.JTextField();
        lblY1 = new javax.swing.JLabel();
        lblY2 = new javax.swing.JLabel();
        lblY3 = new javax.swing.JLabel();
        lblY4 = new javax.swing.JLabel();
        campY1 = new javax.swing.JTextField();
        campY2 = new javax.swing.JTextField();
        campY3 = new javax.swing.JTextField();
        campY4 = new javax.swing.JTextField();
        lblX5 = new javax.swing.JLabel();
        lblY5 = new javax.swing.JLabel();
        lblY6 = new javax.swing.JLabel();
        lblX6 = new javax.swing.JLabel();
        campY5 = new javax.swing.JTextField();
        campY6 = new javax.swing.JTextField();
        lblX7 = new javax.swing.JLabel();
        campY7 = new javax.swing.JTextField();
        campX5 = new javax.swing.JTextField();
        campY8 = new javax.swing.JTextField();
        campX6 = new javax.swing.JTextField();
        campX7 = new javax.swing.JTextField();
        campX8 = new javax.swing.JTextField();
        lblCuadrado1 = new javax.swing.JLabel();
        lblX8 = new javax.swing.JLabel();
        lblY7 = new javax.swing.JLabel();
        lblY8 = new javax.swing.JLabel();
        lblY9 = new javax.swing.JLabel();
        lblX9 = new javax.swing.JLabel();
        lblY10 = new javax.swing.JLabel();
        lblX10 = new javax.swing.JLabel();
        campY9 = new javax.swing.JTextField();
        campY10 = new javax.swing.JTextField();
        campY11 = new javax.swing.JTextField();
        campX9 = new javax.swing.JTextField();
        campX10 = new javax.swing.JTextField();
        campX11 = new javax.swing.JTextField();
        lblCuadrado2 = new javax.swing.JLabel();
        lblX11 = new javax.swing.JLabel();
        lblY11 = new javax.swing.JLabel();
        jButtonCuadro = new javax.swing.JButton();
        jButtonRectangulo = new javax.swing.JButton();
        jButtonTriangulo = new javax.swing.JButton();
        panelPlano = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCuadrado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCuadrado.setText("Cuadrado:");

        lblX1.setText("X1:");

        lblX2.setText("X2:");

        lblX3.setText("X3:");

        lblX4.setText("X4:");

        campX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX1ActionPerformed(evt);
            }
        });

        campX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX3ActionPerformed(evt);
            }
        });

        lblY1.setText("Y1:");

        lblY2.setText("Y2:");

        lblY3.setText("Y3:");

        lblY4.setText("Y4:");

        campY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campY1ActionPerformed(evt);
            }
        });

        lblX5.setText("X2:");

        lblY5.setText("Y3:");

        lblY6.setText("Y4:");

        lblX6.setText("X3:");

        campY5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campY5ActionPerformed(evt);
            }
        });

        lblX7.setText("X4:");

        campX5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX5ActionPerformed(evt);
            }
        });

        campX7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX7ActionPerformed(evt);
            }
        });

        lblCuadrado1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCuadrado1.setText("Rectangulo:");

        lblX8.setText("X1:");

        lblY7.setText("Y1:");

        lblY8.setText("Y2:");

        lblY9.setText("Y2:");

        lblX9.setText("X2:");

        lblY10.setText("Y3:");

        lblX10.setText("X3:");

        campY9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campY9ActionPerformed(evt);
            }
        });

        campX9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX9ActionPerformed(evt);
            }
        });

        campX11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX11ActionPerformed(evt);
            }
        });

        lblCuadrado2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCuadrado2.setText("Triangulo:");

        lblX11.setText("X1:");

        lblY11.setText("Y1:");

        jButtonCuadro.setText("Calcular");
        jButtonCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuadroActionPerformed(evt);
            }
        });

        jButtonRectangulo.setText("Calcular");
        jButtonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRectanguloActionPerformed(evt);
            }
        });

        jButtonTriangulo.setText("Calcular");
        jButtonTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPlanoLayout = new javax.swing.GroupLayout(panelPlano);
        panelPlano.setLayout(panelPlanoLayout);
        panelPlanoLayout.setHorizontalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        panelPlanoLayout.setVerticalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblY11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY11)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTriangulo))
                    .addComponent(lblCuadrado1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblY7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRectangulo))
                    .addComponent(lblCuadrado2)
                    .addComponent(lblCuadrado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblY1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCuadro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX1)
                            .addComponent(campX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY1)
                            .addComponent(campY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX2)
                                    .addComponent(campX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY2)
                                    .addComponent(campY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX3)
                                    .addComponent(campX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY3)
                                    .addComponent(campY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButtonCuadro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX4)
                            .addComponent(campX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY4)
                            .addComponent(campY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCuadrado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX8)
                            .addComponent(campX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY7)
                            .addComponent(campY5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX5)
                                    .addComponent(campX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY8)
                                    .addComponent(campY6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX6)
                                    .addComponent(campX7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY5)
                                    .addComponent(campY7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRectangulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX7)
                            .addComponent(campX8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY6)
                            .addComponent(campY8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCuadrado2)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX11)
                            .addComponent(campX9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY11)
                            .addComponent(campY9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX9)
                            .addComponent(campX10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY9)
                            .addComponent(campY10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTriangulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX10)
                            .addComponent(campX11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY10)
                            .addComponent(campY11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX1ActionPerformed

    }//GEN-LAST:event_campX1ActionPerformed

    private void campX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX3ActionPerformed

    private void campY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campY1ActionPerformed

    private void campY5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campY5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campY5ActionPerformed

    private void campX5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX5ActionPerformed

    private void campX7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX7ActionPerformed

    private void campY9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campY9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campY9ActionPerformed

    private void campX9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX9ActionPerformed

    private void campX11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX11ActionPerformed

    private void jButtonCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuadroActionPerformed
        try {
            int[] aux = new int[8];

            aux[0] = Integer.parseInt(campX1.getText());
            aux[1] = Integer.parseInt(campY1.getText());
            aux[2] = Integer.parseInt(campX2.getText());
            aux[3] = Integer.parseInt(campY2.getText());
            aux[4] = Integer.parseInt(campX3.getText());
            aux[5] = Integer.parseInt(campY3.getText());
            aux[6] = Integer.parseInt(campX4.getText());
            aux[7] = Integer.parseInt(campY4.getText());

            dibujar(aux);
            Cuadrado cuadrado = new Cuadrado((short) (aux[0] - aux[1]));
            JOptionPane.showMessageDialog(this, "Area de la figura:"+cuadrado.getArea(), "Area", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Diligencie los datos!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCuadroActionPerformed

    private void jButtonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRectanguloActionPerformed
        try {
            int[] aux = new int[8];

            aux[0] = Integer.parseInt(campX5.getText());
            aux[1] = Integer.parseInt(campY5.getText());
            aux[2] = Integer.parseInt(campX6.getText());
            aux[3] = Integer.parseInt(campY6.getText());
            aux[4] = Integer.parseInt(campX7.getText());
            aux[5] = Integer.parseInt(campY7.getText());
            aux[6] = Integer.parseInt(campX8.getText());
            aux[7] = Integer.parseInt(campY8.getText());

            dibujar(aux);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Diligencie los datos!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRectanguloActionPerformed

    private void jButtonTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrianguloActionPerformed
        try {
            int[] aux = new int[8];

            aux[0] = Integer.parseInt(campX9.getText());
            aux[1] = Integer.parseInt(campY9.getText());
            aux[2] = Integer.parseInt(campX10.getText());
            aux[3] = Integer.parseInt(campY10.getText());
            aux[4] = Integer.parseInt(campX11.getText());
            aux[5] = Integer.parseInt(campY11.getText());
            aux[6] = Integer.parseInt(campY11.getText());
            aux[7] = Integer.parseInt(campY11.getText());

            dibujar(aux);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Diligencie los datos!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTrianguloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campX1;
    private javax.swing.JTextField campX10;
    private javax.swing.JTextField campX11;
    private javax.swing.JTextField campX2;
    private javax.swing.JTextField campX3;
    private javax.swing.JTextField campX4;
    private javax.swing.JTextField campX5;
    private javax.swing.JTextField campX6;
    private javax.swing.JTextField campX7;
    private javax.swing.JTextField campX8;
    private javax.swing.JTextField campX9;
    private javax.swing.JTextField campY1;
    private javax.swing.JTextField campY10;
    private javax.swing.JTextField campY11;
    private javax.swing.JTextField campY2;
    private javax.swing.JTextField campY3;
    private javax.swing.JTextField campY4;
    private javax.swing.JTextField campY5;
    private javax.swing.JTextField campY6;
    private javax.swing.JTextField campY7;
    private javax.swing.JTextField campY8;
    private javax.swing.JTextField campY9;
    private javax.swing.JButton jButtonCuadro;
    private javax.swing.JButton jButtonRectangulo;
    private javax.swing.JButton jButtonTriangulo;
    private javax.swing.JLabel lblCuadrado;
    private javax.swing.JLabel lblCuadrado1;
    private javax.swing.JLabel lblCuadrado2;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX10;
    private javax.swing.JLabel lblX11;
    private javax.swing.JLabel lblX2;
    private javax.swing.JLabel lblX3;
    private javax.swing.JLabel lblX4;
    private javax.swing.JLabel lblX5;
    private javax.swing.JLabel lblX6;
    private javax.swing.JLabel lblX7;
    private javax.swing.JLabel lblX8;
    private javax.swing.JLabel lblX9;
    private javax.swing.JLabel lblY1;
    private javax.swing.JLabel lblY10;
    private javax.swing.JLabel lblY11;
    private javax.swing.JLabel lblY2;
    private javax.swing.JLabel lblY3;
    private javax.swing.JLabel lblY4;
    private javax.swing.JLabel lblY5;
    private javax.swing.JLabel lblY6;
    private javax.swing.JLabel lblY7;
    private javax.swing.JLabel lblY8;
    private javax.swing.JLabel lblY9;
    private javax.swing.JPanel panelPlano;
    // End of variables declaration//GEN-END:variables

}
