/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanJ
 */
public class Ventana extends javax.swing.JFrame {
    Color[] colores = {Color.WHITE,Color.LIGHT_GRAY,Color.GRAY,Color.DARK_GRAY,Color.BLACK,Color.RED,Color.PINK,Color.ORANGE,Color.YELLOW,Color.GREEN,Color.MAGENTA,Color.CYAN,Color.BLUE};
    
    public ArrayList<IFiguraGeometrica> figuras = new ArrayList();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        jComboColores.setSelectedIndex(0);
        jComboColores.setSelectedIndex(0);
        jComboColores.setSelectedIndex(0);
    }

    public void dibujar(int[] coorX, int[] coorY, Color color) {
        Plano plano = new Plano(coorX, coorY, color);
        plano.setBounds(5, 5, 400, 395);
        panelPlano.removeAll();
        panelPlano.add(plano);
        panelPlano.revalidate();
        panelPlano.repaint();
    }
    
    public void cargar(){
        figuras.forEach((figura) -> {
            if (figura instanceof Rectangulo) {
                // ((Rectangulo) object).obtenerLados(coordenadas);
            }else if(figura instanceof Triangulo){
               // ((Triangulo) figura).prueba();
            }else{
                //((Cuadrado) object).figuras.get(jComboFiguras.getSelectedIndex()).obtenerLados(coordenadas);
            }
        });  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuadrado = new javax.swing.JLabel();
        lblX1 = new javax.swing.JLabel();
        lblX2 = new javax.swing.JLabel();
        lblX3 = new javax.swing.JLabel();
        lblX4 = new javax.swing.JLabel();
        campX1 = new javax.swing.JTextField();
        campX2 = new javax.swing.JTextField();
        campX3 = new javax.swing.JTextField();
        campX4 = new javax.swing.JTextField();
        lblY1 = new javax.swing.JLabel();
        lblY2 = new javax.swing.JLabel();
        lblY3 = new javax.swing.JLabel();
        lblY4 = new javax.swing.JLabel();
        campY1 = new javax.swing.JTextField();
        campY2 = new javax.swing.JTextField();
        campY3 = new javax.swing.JTextField();
        campY4 = new javax.swing.JTextField();
        lblX5 = new javax.swing.JLabel();
        lblY5 = new javax.swing.JLabel();
        lblY6 = new javax.swing.JLabel();
        lblX6 = new javax.swing.JLabel();
        campY5 = new javax.swing.JTextField();
        campY6 = new javax.swing.JTextField();
        lblX7 = new javax.swing.JLabel();
        campY7 = new javax.swing.JTextField();
        campX5 = new javax.swing.JTextField();
        campY8 = new javax.swing.JTextField();
        campX6 = new javax.swing.JTextField();
        campX7 = new javax.swing.JTextField();
        campX8 = new javax.swing.JTextField();
        lblCuadrado1 = new javax.swing.JLabel();
        lblX8 = new javax.swing.JLabel();
        lblY7 = new javax.swing.JLabel();
        lblY8 = new javax.swing.JLabel();
        lblY9 = new javax.swing.JLabel();
        lblX9 = new javax.swing.JLabel();
        lblY10 = new javax.swing.JLabel();
        lblX10 = new javax.swing.JLabel();
        campY9 = new javax.swing.JTextField();
        campY10 = new javax.swing.JTextField();
        campY11 = new javax.swing.JTextField();
        campX9 = new javax.swing.JTextField();
        campX10 = new javax.swing.JTextField();
        campX11 = new javax.swing.JTextField();
        lblCuadrado2 = new javax.swing.JLabel();
        lblX11 = new javax.swing.JLabel();
        lblY11 = new javax.swing.JLabel();
        jButtonCuadro = new javax.swing.JButton();
        jButtonRectangulo = new javax.swing.JButton();
        jButtonTriangulo = new javax.swing.JButton();
        panelPlano = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboColores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboColores1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboColores2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboFiguras = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabelPerimetro = new javax.swing.JLabel();
        jLabelArea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCuadrado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCuadrado.setText("Cuadrado:");

        lblX1.setText("X1:");

        lblX2.setText("X2:");

        lblX3.setText("X3:");

        lblX4.setText("X4:");

        campX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX1ActionPerformed(evt);
            }
        });

        campX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX3ActionPerformed(evt);
            }
        });

        lblY1.setText("Y1:");

        lblY2.setText("Y2:");

        lblY3.setText("Y3:");

        lblY4.setText("Y4:");

        campY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campY1ActionPerformed(evt);
            }
        });

        lblX5.setText("X2:");

        lblY5.setText("Y3:");

        lblY6.setText("Y4:");

        lblX6.setText("X3:");

        campY5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campY5ActionPerformed(evt);
            }
        });

        lblX7.setText("X4:");

        campX5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX5ActionPerformed(evt);
            }
        });

        campX7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX7ActionPerformed(evt);
            }
        });

        lblCuadrado1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCuadrado1.setText("Rectangulo:");

        lblX8.setText("X1:");

        lblY7.setText("Y1:");

        lblY8.setText("Y2:");

        lblY9.setText("Y2:");

        lblX9.setText("X2:");

        lblY10.setText("Y3:");

        lblX10.setText("X3:");

        campY9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campY9ActionPerformed(evt);
            }
        });

        campX9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX9ActionPerformed(evt);
            }
        });

        campX11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campX11ActionPerformed(evt);
            }
        });

        lblCuadrado2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCuadrado2.setText("Triangulo:");

        lblX11.setText("X1:");

        lblY11.setText("Y1:");

        jButtonCuadro.setText("Calcular");
        jButtonCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuadroActionPerformed(evt);
            }
        });

        jButtonRectangulo.setText("Calcular");
        jButtonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRectanguloActionPerformed(evt);
            }
        });

        jButtonTriangulo.setText("Calcular");
        jButtonTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrianguloActionPerformed(evt);
            }
        });

        panelPlano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        panelPlano.setPreferredSize(new java.awt.Dimension(300, 420));

        javax.swing.GroupLayout panelPlanoLayout = new javax.swing.GroupLayout(panelPlano);
        panelPlano.setLayout(panelPlanoLayout);
        panelPlanoLayout.setHorizontalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPlanoLayout.setVerticalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jLabel1.setText("Color:");

        jComboColores.setMaximumRowCount(15);
        jComboColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Gris claro", "Gris", "Gris oscuro", "Negro", "Rojo", "Rosa", "Naranja", "Amarillo", "Verde", "Magenta", "Aguamarina", "Azul"  }));

        jLabel2.setText("Color:");

        jComboColores1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Gris claro", "Gris", "Gris oscuro", "Negro", "Rojo", "Rosa", "Naranja", "Amarillo", "Verde", "Magenta", "Aguamarina", "Azul"  }));

        jLabel3.setText("Color:");

        jComboColores2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Gris claro", "Gris", "Gris oscuro", "Negro", "Rojo", "Rosa", "Naranja", "Amarillo", "Verde", "Magenta", "Aguamarina", "Azul"  }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Propiedades:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Perimetro:");

        jLabel6.setText("Escoja una de las figuras:");

        jComboFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Seleccione"}));
        jComboFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFigurasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Area:");

        jLabelPerimetro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelPerimetro.setForeground(new java.awt.Color(0, 102, 255));

        jLabelArea.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelArea.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuadrado1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblY7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRectangulo))
                    .addComponent(lblCuadrado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblY1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCuadro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboColores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblX11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campX9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblY11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblY10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campY11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTriangulo))
                    .addComponent(lblCuadrado2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboColores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelPerimetro))
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelArea))
                            .addComponent(jComboFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(199, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX1)
                            .addComponent(campX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY1)
                            .addComponent(campY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX2)
                                    .addComponent(campX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY2)
                                    .addComponent(campY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX3)
                                    .addComponent(campX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY3)
                                    .addComponent(campY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButtonCuadro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX4)
                            .addComponent(campX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY4)
                            .addComponent(campY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblCuadrado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX8)
                            .addComponent(campX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY7)
                            .addComponent(campY5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX5)
                                    .addComponent(campX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY8)
                                    .addComponent(campY6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX6)
                                    .addComponent(campX7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblY5)
                                    .addComponent(campY7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRectangulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX7)
                            .addComponent(campX8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY6)
                            .addComponent(campY8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboColores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelPlano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelPerimetro))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabelArea)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuadrado2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX11)
                            .addComponent(campX9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY11)
                            .addComponent(campY9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX9)
                            .addComponent(campX10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY9)
                            .addComponent(campY10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTriangulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX10)
                            .addComponent(campX11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY10)
                            .addComponent(campY11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboColores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX1ActionPerformed

    }//GEN-LAST:event_campX1ActionPerformed

    private void campX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX3ActionPerformed

    private void campY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campY1ActionPerformed

    private void campY5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campY5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campY5ActionPerformed

    private void campX5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX5ActionPerformed

    private void campX7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX7ActionPerformed

    private void campY9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campY9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campY9ActionPerformed

    private void campX9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX9ActionPerformed

    private void campX11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campX11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campX11ActionPerformed

    private void jButtonCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuadroActionPerformed
        try {
            int[] coorX = new int[4];
            int[] coorY = new int[4];

            coorX[0] = Integer.parseInt(campX1.getText())*39;
            coorY[0] = 395-(Integer.parseInt(campY1.getText())*39);
            coorX[1] = Integer.parseInt(campX2.getText())*39;
            coorY[1] = 395-(Integer.parseInt(campY2.getText())*39);
            coorX[2] = Integer.parseInt(campX3.getText())*39;
            coorY[2] = 395-(Integer.parseInt(campY3.getText())*39);
            coorX[3] = Integer.parseInt(campX4.getText())*39;
            coorY[3] = 395-(Integer.parseInt(campY4.getText())*39);
            //IFiguraGeometrica cuadrado = new Cuadrado(coorX, coorY, colores[jComboColores.getSelectedIndex()]);
            //figuras.add(cuadrado);
            dibujar(coorX, coorY, colores[jComboColores.getSelectedIndex()]);
            jComboFiguras.addItem(figuras.size()+". Cuadrado "+"("+campX1.getText()+","+campY1.getText()+")"+"("+campX2.getText()+","+campY2.getText()+")"+"("+campX3.getText()+","+campY3.getText()+")"+"("+campX4.getText()+","+campY4.getText()+")"+jComboColores.getSelectedItem());
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Diligencie los datos!", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonCuadroActionPerformed

    private void jButtonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRectanguloActionPerformed
        try {
            int[] coorX = new int[4];
            int[] coorY = new int[4];

            coorX[0] = Integer.parseInt(campX5.getText())*39;
            coorY[0] = 395-(Integer.parseInt(campY5.getText())*39);
            coorX[1] = Integer.parseInt(campX6.getText())*39;
            coorY[1] = 395-(Integer.parseInt(campY6.getText())*39);
            coorX[2] = Integer.parseInt(campX7.getText())*39;
            coorY[2] = 395-(Integer.parseInt(campY7.getText())*39);
            coorX[3] = Integer.parseInt(campX8.getText())*39;
            coorY[3] = 395-(Integer.parseInt(campY8.getText())*39);
            
            //IFiguraGeometrica rectangulo = new Rectangulo(coorX, coorY, colores[jComboColores1.getSelectedIndex()]);
            //figuras.add(rectangulo);
            dibujar(coorX, coorY, colores[jComboColores1.getSelectedIndex()]);
            jComboFiguras.addItem(figuras.size()+". Rectangulo "+"("+campX5.getText()+","+campY5.getText()+")"+"("+campX6.getText()+","+campY6.getText()+")"+"("+campX7.getText()+","+campY7.getText()+")"+"("+campX8.getText()+","+campY8.getText()+")"+jComboColores1.getSelectedItem());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Diligencie los datos!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRectanguloActionPerformed

    private void jButtonTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrianguloActionPerformed
        try {
            double[] coorX = new double[3];
            double[] coorY = new double[3];
            coorX[0] = Integer.parseInt(campX9.getText());
            coorY[0] = Integer.parseInt(campY9.getText());
            coorX[1] = Integer.parseInt(campX10.getText());
            coorY[1] = Integer.parseInt(campY10.getText());
            coorX[2] = Integer.parseInt(campX11.getText());
            coorY[2] = Integer.parseInt(campY11.getText());
            
            int[] pxlX = new int[3];
            int[] pxlY = new int[3];
            pxlX[0] = Integer.parseInt(campX9.getText())*39;
            pxlY[0] = 395-(Integer.parseInt(campY9.getText())*39);
            pxlX[1] = Integer.parseInt(campX10.getText())*39;
            pxlY[1] = 395-(Integer.parseInt(campY10.getText())*39);
            pxlX[2] = Integer.parseInt(campX11.getText())*39;
            pxlY[2] = 395-(Integer.parseInt(campY11.getText())*39);
            
            IFiguraGeometrica triangulo = new Triangulo(coorX, coorY, colores[jComboColores2.getSelectedIndex()]);
            figuras.add(triangulo);
            dibujar(pxlX, pxlY, colores[jComboColores2.getSelectedIndex()]);
            jLabelArea.setText(Double.toString(((Triangulo)triangulo).hallarArea(((Triangulo)triangulo).obtenerLados())));
            jLabelPerimetro.setText(Double.toString(((Triangulo)triangulo).hallarPerimetro(((Triangulo)triangulo).obtenerLados())));            
            jComboFiguras.addItem(figuras.size()+". Triangulo "+"("+campX9.getText()+","+campY9.getText()+")"+"("+campX10.getText()+","+campY10.getText()+")"+"("+campX11.getText()+","+campY11.getText()+")"+jComboColores2.getSelectedItem());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Diligencie los datos!", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonTrianguloActionPerformed

    private void jComboFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFigurasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFigurasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campX1;
    private javax.swing.JTextField campX10;
    private javax.swing.JTextField campX11;
    private javax.swing.JTextField campX2;
    private javax.swing.JTextField campX3;
    private javax.swing.JTextField campX4;
    private javax.swing.JTextField campX5;
    private javax.swing.JTextField campX6;
    private javax.swing.JTextField campX7;
    private javax.swing.JTextField campX8;
    private javax.swing.JTextField campX9;
    private javax.swing.JTextField campY1;
    private javax.swing.JTextField campY10;
    private javax.swing.JTextField campY11;
    private javax.swing.JTextField campY2;
    private javax.swing.JTextField campY3;
    private javax.swing.JTextField campY4;
    private javax.swing.JTextField campY5;
    private javax.swing.JTextField campY6;
    private javax.swing.JTextField campY7;
    private javax.swing.JTextField campY8;
    private javax.swing.JTextField campY9;
    private javax.swing.JButton jButtonCuadro;
    private javax.swing.JButton jButtonRectangulo;
    private javax.swing.JButton jButtonTriangulo;
    private javax.swing.JComboBox<String> jComboColores;
    private javax.swing.JComboBox<String> jComboColores1;
    private javax.swing.JComboBox<String> jComboColores2;
    private javax.swing.JComboBox<String> jComboFiguras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelPerimetro;
    private javax.swing.JLabel lblCuadrado;
    private javax.swing.JLabel lblCuadrado1;
    private javax.swing.JLabel lblCuadrado2;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX10;
    private javax.swing.JLabel lblX11;
    private javax.swing.JLabel lblX2;
    private javax.swing.JLabel lblX3;
    private javax.swing.JLabel lblX4;
    private javax.swing.JLabel lblX5;
    private javax.swing.JLabel lblX6;
    private javax.swing.JLabel lblX7;
    private javax.swing.JLabel lblX8;
    private javax.swing.JLabel lblX9;
    private javax.swing.JLabel lblY1;
    private javax.swing.JLabel lblY10;
    private javax.swing.JLabel lblY11;
    private javax.swing.JLabel lblY2;
    private javax.swing.JLabel lblY3;
    private javax.swing.JLabel lblY4;
    private javax.swing.JLabel lblY5;
    private javax.swing.JLabel lblY6;
    private javax.swing.JLabel lblY7;
    private javax.swing.JLabel lblY8;
    private javax.swing.JLabel lblY9;
    private javax.swing.JPanel panelPlano;
    // End of variables declaration//GEN-END:variables

}
